name: Update Playlist Token

on:
  schedule:
    - cron: "*/30 * * * *"  # Запускается каждые 30 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновленная версия

      - name: Set up Python
        uses: actions/setup-python@v3  # Обновленная версия
        with:
          python-version: '3.9'  # Указываем точную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium webdriver-manager  # Установка дополнительных библиотек

      - name: Configure Git user
        run: |
          git config --global user.email "you@example.com"  # Укажите свой email
          git config --global user.name "Your Name"  # Укажите свое имя

      - name: Update playlist with new token
        run: |
          echo "MY_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}"  # Проверим доступность токена
          python3 update_playlist.py  # Запуск вашего скрипта

      - name: Check for changes before pushing
        run: |
          git diff  # Проверяем изменения

      - name: Force add the playlist file
        run: |
          git add -f playlist.m3u  # Принудительное добавление файла
          git commit -m "Update playlist with new token" || echo "No changes to commit"  # Если изменений нет, пропускаем

      - name: Push changes to GitHub repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Передаем GITHUB_TOKEN в окружение
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vtal999/playlist-updater.git  # Используем GITHUB_TOKEN для аутентификации
          
      - name: Check playlist file contents before and after
        run: |
          cat playlist.m3u  # Печать содержимого файла для проверки







