name: Update Playlist Token

on:
  schedule:
    - cron: "*/30 * * * *"  # Запускается каждые 30 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-playlist:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновленная версия

      - name: Set up Python
        uses: actions/setup-python@v3  # Обновленная версия
        with:
          python-version: '3.9'  # Указываем точную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Используем requirements.txt для установки зависимостей

      - name: Configure Git user
        run: |
          git config --global user.email "you@example.com"  # Укажите свой email
          git config --global user.name "Your Name"  # Укажите свое имя

      - name: Update playlist with new token
        run: |
          setx GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"  # Передаем токен в окружение для PowerShell
          python3 update_playlist.py  # Запуск скрипта

      - name: Force add the playlist file and commit
        run: |
          git add -f playlist.m3u  # Принудительное добавление файла
          git commit -m "Update playlist with new token" || echo "No changes to commit"  # Если изменений нет, пропускаем

      - name: Push changes
        run: |
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vtal999/playlist-updater.git  # Принудительный пуш
