name: Update Playlist Token

on:
  schedule:
    - cron: "*/30 * * * *"  # Запускается каждые 30 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Указываем версию Python (например, 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Configure Git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Update playlist with new token
        run: |
          python3 update_playlist.py  # Запуск вашего скрипта

      - name: Check playlist file contents before and after
        run: |
          cat playlist.m3u  # Печать содержимого файла для проверки

      - name: Force add the playlist file
        run: |
          git add -f playlist.m3u  # Принудительное добавление файла
          git commit -m "Update playlist with new token"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используем автоматический GITHUB_TOKEN





