name: Update Playlist Token

on:
  schedule:
    - cron: "*/10 * * * *"  # Запускается каждые 30 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновленная версия

      - name: Set up Python
        uses: actions/setup-python@v3  # Обновленная версия
        with:
          python-version: '3.x'  # Указываем версию Python (например, 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Configure Git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Update playlist with new token
        run: |
          echo "MY_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}"  # Проверим доступность токена
          python3 update_playlist.py  # Запуск вашего скрипта

      - name: Check for changes before pushing
        run: |
          git diff  # Проверяем изменения

      - name: Force add the playlist file
        run: |
          git add -f playlist.m3u  # Принудительное добавление файла
          git commit -m "Update playlist with new token" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MY_PERSONAL_TOKEN }}@github.com/vtal999/playlist-updater.git

      - name: Check playlist file contents before and after
        run: |
          cat playlist.m3u  # Печать содержимого файла для проверки


